package fr.jerome.climbinggymlog.models;

/**
 * Classe représentant une Personne
 * Created by jerome on 25/01/15.
 */
public abstract class Personne {

    protected int id;
    protected String nom;
    protected String prenom;
    protected int age;
    protected String email;

    /**
     * Constructeur d'une Personne avec spécification de l'id
     *
     * @param id de la personne dans la DB
     * @param nom de la personne
     * @param prenom de la personne
     * @param age de la personne
     */
    public Personne(int id, String nom, String prenom, int age, String email) {

        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.age = age;
        this.email = email;
    }

    /**
     * Constructeur d'une Personne avec l'id, id generated by the DB
     *
     * @param nom de la personne
     * @param prenom de la personne
     * @param age de la personne
     */
    public Personne(String nom, String prenom, int age, String email) {

        this.nom = nom;
        this.prenom = prenom;
        this.age = age;
        this.email = email;
    }

    /**
     * Default constructor for a Personne
     */
    public Personne() {

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "Personne{" +
                "id=" + id +
                ", nom='" + nom + '\'' +
                ", prenom='" + prenom + '\'' +
                ", age=" + age +
                ", email='" + email + '\'' +
                '}';
    }
}
