package fr.jerome.climbinggymlog.models;

/**
 * Classe représentant une Personne
 * Created by jerome on 25/01/15.
 */
public abstract class Personne {

    protected long id;
    protected String nom;
    protected String prenom;
    protected int age;

    /**
     * Constructor for re create a Personnne
     *
     * @param id de la personne dans la DB
     * @param nom de la personne
     * @param prenom de la personne
     * @param age de la personne
     */
    public Personne(long id, String nom, String prenom, int age) {

        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.age = age;
    }

    /**
     * Constructor for a new Personne, id generated by the DB
     *
     * @param nom de la personne
     * @param prenom de la personne
     * @param age de la personne
     */
    public Personne(String nom, String prenom, int age) {

        this.nom = nom;
        this.prenom = prenom;
        this.age = age;

    }

    /**
     * Default constructor for a Personne
     */
    protected Personne() {

    }

    public long getId() {

        return id;
    }

    public void setId(long id) {

        this.id = id;
    }

    public String getNom() {

        return nom;
    }

    public void setNom(String nom) {

        this.nom = nom;
    }

    public String getPrenom() {

        return prenom;
    }

    public void setPrenom(String prenom) {

        this.prenom = prenom;
    }

    public int getAge() {

        return age;
    }

    public void setAge(int age) {

        this.age = age;
    }

    @Override
    public String toString() {

        return  "_id" + id + "\n" +
                "nom : " + nom + "\n" +
                "prenom : " + prenom + "\n" +
                "age : " + age;
    }
}
